fjernet snyk actions, og rettet opp litt et par andre steder

diff --git a/slack-notify/action.yaml b/slack-notify/action.yaml
--- a/slack-notify/action.yaml
+++ b/slack-notify/action.yaml
@@ -182,6 +182,11 @@ runs:
           )
         PY
         
+        if [[ -z "${SLACK_WEBHOOK}" ]]; then
+          echo "SLACK_WEBHOOK is empty; cannot send Slack notification" >&2
+          exit 1
+        fi
+  
         curl \
           --fail-with-body \
           --silent \
