prøver å sjekke status ved å skive ut http status til slutt

diff --git a/.github/workflows/clean.yaml b/.github/workflows/clean.yaml
--- a/.github/workflows/clean.yaml
+++ b/.github/workflows/clean.yaml
@@ -62,7 +62,16 @@ jobs:
               PKG="${REPOSITORY_NAME}%2F${{ inputs.package }}"
             fi
           fi
-          TOTAL=$(curl -s -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.token }}" "https://api.github.com/orgs/navikt/packages/${{ inputs.type }}/$PKG/versions?per_page=100" | jq 'length')
+          curl -w "%{http_code}" -s -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.token }}" "https://api.github.com/orgs/navikt/packages/${{ inputs.type }}/$PKG/versions?per_page=100" > tmp.json
+          STATUS=$(tail -1 tmp.json)
+          if [ "$STATUS" != "200" ]
+          then
+              echo "fetching of packages failed with status $STATUS"
+              head -n -1 tmp.json
+              exit 1
+          fi
+          cat tmp.json | tail -n -1 > tmp2.json
+          TOTAL=$(cat tmp2.json | jq 'length')
           echo "package has $TOTAL versions (100 means 100 or more) before cleanup" >> $GITHUB_STEP_SUMMARY
           TAIL=$(echo $TOTAL - ${{ inputs.versions-to-keep }} | bc)
           if [ $TAIL -gt ${{ inputs.old-versions-to-delete }} ]
@@ -72,7 +81,7 @@ jobs:
           if [ $TAIL -gt 0 ]
           then
             echo "will attempt to delete $TAIL versions" >> $GITHUB_STEP_SUMMARY
-            TRANSFORMED=$(curl -s -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.token }}" "https://api.github.com/orgs/navikt/packages/${{ inputs.type }}/$PKG/versions?per_page=100" | jq "[.[] |{id: .id, created_at: .created_at, version: .metadata.container.tags[0] }]" | jq ".[-$TAIL:]")
+            TRANSFORMED=$(cat tmp.json | jq "[.[] |{id: .id, created_at: .created_at, version: .metadata.container.tags[0] }]" | jq ".[-$TAIL:]")
             echo "will delete the following packages from $REPOSITORY_NAME:"
             echo $TRANSFORMED | jq
             VERSIONS=$(echo $TRANSFORMED | jq ".[] .id" | tr '\012' ' ')
